model:
  img_encoder: "clip-ViT-L-14"
  text_encoder: "clip-ViT-L-14"
  image_size: 336
  batch_size: 64

vector_db:
  name: "vespa"
  rank_profile: "image_rank"  # or "hybrid_rank"

images:
  name: "vit_L_14"
  path: "data"
