model:
  img_encoder: "clip-ViT-B-32"
  text_encoder: "clip-ViT-B-32"
  image_size: 224
  batch_size: 64

vector_db:
  name: "vespa"
  rank_profile: "image_rank"  # or "hybrid_rank"

images:
  name: "vit_b_32"
  path: "data"
